In [ ]:
!conda install dask

In [83]:
import os

In [128]:
X_train, X_test, y_train, y_test = get_Xy_train_test()

In [107]:
train_model(X_train, y_train, epochs=20)

Train on 13986 samples, validate on 4663 samples
Epoch 1/10
13986/13986 [==============================] - 4s 269us/step - loss: 10.2503 - acc: 0.1705 - val_loss: 7.0374 - val_acc: 0.2642
Epoch 2/10
13986/13986 [==============================] - 2s 157us/step - loss: 5.1720 - acc: 0.3140 - val_loss: 4.6928 - val_acc: 0.3337
Epoch 3/10
13986/13986 [==============================] - 2s 127us/step - loss: 4.5004 - acc: 0.3795 - val_loss: 4.2204 - val_acc: 0.4261
Epoch 4/10
13986/13986 [==============================] - 2s 124us/step - loss: 4.1228 - acc: 0.4235 - val_loss: 4.0363 - val_acc: 0.4441
Epoch 5/10
13986/13986 [==============================] - 2s 128us/step - loss: 4.0082 - acc: 0.4387 - val_loss: 3.9491 - val_acc: 0.4649
Epoch 6/10
13986/13986 [==============================] - 2s 122us/step - loss: 3.9401 - acc: 0.4581 - val_loss: 3.9057 - val_acc: 0.4724
Epoch 7/10
13986/13986 [==============================] - 2s 127us/step - loss: 3.9071 - acc: 0.4668 - val_loss: 3.8586 - val_acc: 0.4855
Epoch 8/10
13986/13986 [==============================] - 2s 129us/step - loss: 3.8607 - acc: 0.4798 - val_loss: 3.8163 - val_acc: 0.4838
Epoch 9/10
13986/13986 [==============================] - 2s 134us/step - loss: 3.8346 - acc: 0.4831 - val_loss: 3.7953 - val_acc: 0.5016
Epoch 10/10
13986/13986 [==============================] - 2s 119us/step - loss: 3.7850 - acc: 0.4937 - val_loss: 3.7387 - val_acc: 0.5044

[########################################] | 100% Completed |  6min 39.1s
[########################################] | 100% Completed |  6min 39.2s

In [138]:
len(out)

2058612

In [148]:
train_df_full.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,class
0,28.994889,0.708649,-13.559385,-19.597086,-31.905214,-24.984053,-32.022156,-28.530975,-23.116606,-15.862965,-9.933812,-3.623045,4.127296,23
1,47.000106,-2.745054,-11.711429,-12.742342,-26.065414,-18.878821,-32.612539,-27.266612,-17.825662,-13.635895,-8.555331,0.188485,7.914023,23
2,52.384181,-15.690961,-11.028046,-10.847483,-21.902014,-11.937326,-29.926201,-24.379022,-15.855332,-11.728364,-8.372347,9.350079,13.421100,23
3,49.757766,-31.209891,-13.866855,-6.127108,-17.770011,-6.742553,-23.268744,-23.429808,-15.894561,-11.765930,-8.409864,5.319368,10.809205,23
4,36.399844,-35.703060,-10.133038,1.544480,-15.445047,-3.867544,-25.802416,-29.317975,-18.734423,-14.691632,-11.514286,1.261643,10.063241,23

In [149]:
y = pd.get_dummies(train_df_full["class"])

In [151]:
X = train_df_full.drop("class", axis=1)

In [152]:
train_model(X, y, 1)

Train on 1543959 samples, validate on 514653 samples
Epoch 1/1
1543959/1543959 [==============================] - 410s 265us/step - loss: 2.8389 - acc: 0.2548 - val_loss: 2.8481 - val_acc: 0.2630

In [2]:
import numpy as np
from scipy.stats import mode
import pandas as pd

In [ ]:
def convert_folder_to_single_df(folder, new_fn):
    ProgressBar().register()

    df = dd.read_csv("../data/freesound-ml/{}/*.csv".format(folder))

    with ProgressBar():
        out = df.compute()

    train_df_full = out.drop(out.columns[0], axis=1)
    train_df_full = train_df_full.reset_index().drop("index", axis=1)
    train_df_full.to_csv("../data/freesound-ml/{}.csv".format(new_fn), index=False)

In [199]:
def get_result(folder, fn, model):
    sample_df = pd.read_csv("../data/freesound-ml/{}/{}".format(folder, fn))
    
    # Drop dodgy index row
    sample_df.drop(sample_df.columns[0], axis=1, inplace=True)
    
    y = sample_df["class"]
    testX = sample_df.drop("class", axis=1)
    pred = mode(model.predict_classes(testX))[0][0]
    
    row = {}
    row["pred"] = pred
    row["y"] = y.iloc[0]
    row["correct"] = int(pred == y.iloc[0])
    result = pd.DataFrame(data=row, index=[fn])
    return result

In [200]:
get_result("audio_test_mfcc", "007759c4.csv", model)

              pred   y  correct
007759c4.csv    18  30        0

In [178]:
result = pd.DataFrame()
result["hello"] = "hello"
result

In [179]:
result

Empty DataFrame
Columns: [hello]
Index: []

In [72]:
df = pd.read_csv("../data/freesound-ml/audio_train_mfcc_weighted/00044347.csv", index_col=0)

In [98]:
xCols = list(range(13))

for col_i in range(len(xCols)):
    if col_i != 0:
        print(col_i, col_i - 1)
        
    if(col_i != (len(xCols) -1)):
        print(col_i, col_i + 1)

0
0 1
plusser
0 1
1
1 2
minuser
1 0
plusser
1 2
2
2 3
minuser
2 1
plusser
2 3
3
3 4
minuser
3 2
plusser
3 4
4
4 5
minuser
4 3
plusser
4 5
5
5 6
minuser
5 4
plusser
5 6
6
6 7
minuser
6 5
plusser
6 7
7
7 8
minuser
7 6
plusser
7 8
8
8 9
minuser
8 7
plusser
8 9
9
9 10
minuser
9 8
plusser
9 10
10
10 11
minuser
10 9
plusser
10 11
11
11 12
minuser
11 10
plusser
11 12
12
12 13
minuser
12 11

In [80]:
%%time
eng = engineer_features(df)

Wall time: 171 ms

In [69]:
df.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,class,fn,sample_weight
0,28.994889,0.708649,-13.559385,-19.597086,-31.905214,-24.984053,-32.022156,-28.530975,-23.116606,-15.862965,-9.933812,-3.623045,4.127296,23,00044347.wav,0.5
1,47.000106,-2.745054,-11.711429,-12.742342,-26.065414,-18.878821,-32.612539,-27.266612,-17.825662,-13.635895,-8.555331,0.188485,7.914023,23,00044347.wav,0.5
2,52.384181,-15.690961,-11.028046,-10.847483,-21.902014,-11.937326,-29.926201,-24.379022,-15.855332,-11.728364,-8.372347,9.350079,13.421100,23,00044347.wav,0.5
3,49.757766,-31.209891,-13.866855,-6.127108,-17.770011,-6.742553,-23.268744,-23.429808,-15.894561,-11.765930,-8.409864,5.319368,10.809205,23,00044347.wav,0.5
4,36.399844,-35.703060,-10.133038,1.544480,-15.445047,-3.867544,-25.802416,-29.317975,-18.734423,-14.691632,-11.514286,1.261643,10.063241,23,00044347.wav,0.5
5,24.328775,-41.860080,-9.514523,2.909384,-18.490888,-10.064715,-33.489379,-33.858076,-18.579214,-9.104512,-9.542894,2.429307,11.283724,23,00044347.wav,0.5
6,16.089437,-53.661225,-19.580502,2.926625,-16.857164,-13.275325,-36.163159,-35.856928,-23.451684,-8.323283,-7.565832,2.771864,13.279952,23,00044347.wav,0.5
7,6.093392,-56.455447,-21.162835,7.461073,-19.947574,-15.624281,-32.689671,-35.015853,-28.637608,-5.612471,-4.692711,3.049808,17.870792,23,00044347.wav,0.5
8,-5.533801,-59.002908,-23.301801,5.847528,-22.647653,-13.359681,-30.552347,-34.585687,-28.716599,-0.640943,-0.642572,1.493409,15.194965,23,00044347.wav,0.5
9,-7.855196,-61.373780,-25.533740,3.191962,-22.134122,-15.600070,-32.190204,-30.013125,-25.999360,-6.807522,-7.893611,-1.752158,16.609543,23,00044347.wav,0.5

In [70]:
eng.head(10)

,0,1,2,3,4,5,6,7,8,9,...,3_roll_50_std,4_roll_50_std,5_roll_50_std,6_roll_50_std,7_roll_50_std,8_roll_50_std,9_roll_50_std,10_roll_50_std,11_roll_50_std,12_roll_50_std
49,1.673477,-1.688544,-0.319665,-0.182316,-0.989239,-0.567053,-1.542206,-1.444385,-1.409383,1.514426,...,0.508723,0.322891,0.639896,0.285976,0.510830,0.491851,1.330852,0.686685,0.918702,0.908944
50,1.754079,-1.638307,-0.003337,0.047616,-0.331282,-0.733596,-1.556799,-1.943076,-1.772940,0.366488,...,0.440749,0.324116,0.621611,0.289699,0.510430,0.481379,1.246787,0.682769,0.936363,0.947341
51,1.748658,-1.863683,0.015147,-0.358753,-0.592125,-0.619426,-1.263298,-2.203791,-1.852702,0.009847,...,0.407186,0.323263,0.620814,0.289377,0.511020,0.481321,1.180451,0.673488,0.943018,0.948870
52,1.673869,-1.969182,-0.104208,-0.770589,-0.729477,-0.181255,-0.977214,-1.975321,-1.053679,0.784951,...,0.384905,0.318508,0.615046,0.291158,0.509569,0.499472,1.135583,0.663199,0.911937,0.951254
53,1.633315,-1.926481,-0.081505,-0.636449,-0.720123,-0.577976,-0.960551,-1.974436,-1.331556,0.804762,...,0.379057,0.304698,0.584050,0.279029,0.506734,0.507819,1.084851,0.651578,0.897503,0.949745
54,1.596899,-2.048160,-0.067802,-0.604741,-1.059480,-0.775545,-1.141468,-2.296139,-1.506394,-0.058347,...,0.378837,0.288423,0.527643,0.271956,0.506904,0.510139,0.979947,0.650563,0.902239,0.946550
55,1.562386,-2.088891,-0.033429,-0.603491,-1.192730,-0.911276,-0.961075,-2.494475,-1.363172,-0.244755,...,0.375876,0.283194,0.511850,0.273781,0.500608,0.515072,0.942735,0.643512,0.906235,0.960845
56,1.554260,-2.099217,-0.234885,-0.717359,-1.299922,-1.217846,-0.821785,-2.140556,-1.140096,0.505376,...,0.374023,0.274977,0.514343,0.274168,0.482440,0.511743,0.909878,0.635721,0.900075,0.964299
57,1.534479,-2.100114,-0.426780,-0.426735,-1.373066,-1.448641,-0.908446,-2.028700,-1.650324,0.045578,...,0.351861,0.276693,0.528003,0.276997,0.466155,0.465656,0.896320,0.598239,0.891619,0.954861
58,1.505980,-2.021422,-0.478700,-0.258312,-1.026503,-0.737433,-0.903877,-1.754644,-1.013854,0.555154,...,0.336582,0.270776,0.521268,0.280267,0.451559,0.426132,0.897346,0.512448,0.889274,0.954766